version: "2"

services:
  geodata:
    image: mdillon/postgis:9.6
    ports:
      - '5432:5432'
    volumes:
      - ./geodata/database:/var/lib/postgresql/data
      - ./geodata/datasets:/datasets
      - ./geodata/initdb:/docker-entrypoint-initdb.d
    environment:
      - GEODATASETS=BAG
#      - BGT # no support yet
#      - BRT # no support yet
    restart: unless-stopped
