version: "2"

services:
  geodata:
#    image: mdillon/postgis:9.6
    build:
      context: geodata
    ports:
      - '5432:5432'
    volumes:
      - ./geodata/database:/var/lib/postgresql/data
      - ./geodata/datasets:/datasets
      - ./geodata/initdb:/docker-entrypoint-initdb.d
    environment:
      # Standaard wordt er geen dataset geladen!
      - GEODATASETS=

      # Kies hier een combinatie van welke datasets je wil laden. Je kan deze op een later moment ook nog toevoegen.
      # - GEODATASETS=bag
      # - GEODATASETS=bag,brt
    restart: unless-stopped
